# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Corsinvest.cv4pve.diag
PackageVersion: 1.9.0
InstallerType: portable
Commands:
- cv4pve-diag
ReleaseDate: 2025-12-12
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-diag/releases/download/v1.9.0/cv4pve-diag.exe-win-x64.zip
  InstallerSha256: PLACEHOLDER_HASH_X64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cv4pve-diag.exe
    PortableCommandAlias: cv4pve-diag
- Architecture: x86
  InstallerUrl: https://github.com/Corsinvest/cv4pve-diag/releases/download/v1.9.0/cv4pve-diag.exe-win-x86.zip
  InstallerSha256: PLACEHOLDER_HASH_X86
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cv4pve-diag.exe
    PortableCommandAlias: cv4pve-diag
- Architecture: arm64
  InstallerUrl: https://github.com/Corsinvest/cv4pve-diag/releases/download/v1.9.0/cv4pve-diag.exe-win-arm64.zip
  InstallerSha256: PLACEHOLDER_HASH_ARM64
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: cv4pve-diag.exe
    PortableCommandAlias: cv4pve-diag
ManifestType: installer
ManifestVersion: 1.10.0
